version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # For development only - mount source code for hot-reloading
      # - ./src:/app/src
      # For production, you might want to mount nginx config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf